import LocalizedStrings from 'react-native-localization';
const strings = new LocalizedStrings({
  en: {
    welcome: 'WELCOME!',
    emailOrPhone: 'Email or Phone No.',
    password: 'Password',
    login: 'Log In',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    changeLanguage: 'Change Language',
    signUp2: 'Sign Up',
    enterFullName: 'Enter Full Name',
    enterEmailId: 'Enter Email Id',
    enterPhoneNo: 'Enter Phone No',
    confirmPassword: 'Confirm Password',
    newPassword: 'New Password',
    enterNewPassword:'Enter New Password',
    resetPassword: 'Reset Password',
    sendOtp: 'Send OTP',
    usePhoneNumber: 'Use Phone Number',
    useEmail: 'Use Email',
    verification: 'Verification',
    enterOtpReceived: 'Resend OTP in',
    verify: 'VERIFY',
    didntReceivedOtp: 'Didn\'t receive OTP?',
    resendAgain: 'Resend again',
    otpError: "'OTP should be exactly 6 characters long",
    new: 'NEW',
    addImagesGallery: 'Add Images from gallery',
    createCard: 'Create Your Own Card',
    editProfile: 'EDIT PROFILE',
    save: 'SAVE',
    contactUs: 'Contact Us',
    aboutUs: 'About Us',
    logout: 'Logout',
    privacyPolicy: 'Privacy & Policy',
    termsCondition: 'Terms & Condition',
    fullNameRequired: 'Full Name is required',
    fullNameError: 'Full Name can only contain letters and spaces',
    emailRequired: 'Email is required',
    emailError: 'Invalid email format',
    phoneNoRequired: 'Phone Number is required',
    phoneNoError: 'Invalid phone number format',
    passwordRequired: 'Password is required',
    messageRequired: 'Message is required',
    confirmPasswordRequired: 'Confirm Password is required',
    confirmPasswordError: 'Passwords do not match',
    imageDownloaded: 'Image downloaded!',
    liked: 'Liked!',
    enterTextHere: 'Enter Text Here ',
    changeYourName: 'Change Your Name',
    change: 'Change',
    name: 'Name',
    edit: 'Edit',
    selectImage: 'Select Image',
    changeName: 'Change Name',
    selectBackGround: 'Select BackGround',
    enterText: 'Enter Text',
    getInTouch: 'Get In Touch',
    enterYourName: 'Enter Your Name',
    enterYourMessage: 'Enter Your Message',
    submit: 'SUBMIT',
    settings: 'Settings',
    changeTextColor: 'Change Text Color',
    changeInfoColor: 'Change Info Color',
    changeNameColor: 'Change Name Color',
    enterBirthdate: 'Enter Birthdate',
    birthdateRequired: 'Please select your birthdate',
    //category
    goodMorning: 'Good Morning',
    goodNight: 'Good Night',
    love: 'Love',
    motivational: 'Motivational',
    festival: 'Festival',
    specialDay: 'Special Day',
    devotional: 'Devotional',
    birthday: 'Birthday',

    // about us section
    heading1: 'Make Your Daily',
    heading2: 'Special Status On Socifly',
    dearUsers: 'Dear Users,',
    sociflyApp: '‘SOCIFLY APP’',
    point1:
      'Have a warm and helpful greeting from me. I am Dhiraj Gajendra Navlakhe the owner of this ',
    point2:
      '. I have completed advanced diploma in graphic designing and animation from IMR College Jalgaon, Maharashtra.',
    point3:
      'After that I am working as a freelance graphic designer from last 11 years. I am working with leading publication houses and advertising agencies from India, UK, US and Australia. Some of my clients are as follows.',
    point4:
      'Now I am starting this new app for all of you so that all of you can send your wishes to your friends, relatives and customers in very special way to create a new bonding with all of them.',
    point5: 'Kindly use the',
    point6: 'and give your love and likes to it.',
    point7: 'Also share the app and rate this app on Play Store.',
    point8: 'Have a nice day.',
    point9: 'Thank you',

    place1: 'Youkiyoto Publishing (Canada)',
    place2: 'Shildcrest Publishing (London, UK)',
    place3: 'Atmosphere Press (Austin, USA)',
    place4: 'Zorba Books (Gurgaon, India)',
    place5: 'Varada Prakashan (Pune, India)',
    place6: 'Youtbook (Chennai, India)',
  },
  hi: {
    welcome: 'आपका स्वागत है',
    emailOrPhone: 'ईमेल या फ़ोन नंबर',
    password: 'पासवर्ड',
    login: 'लॉग इन करें',
    forgotPassword: 'पासवर्ड भूल गए?',
    noAccount: 'खाता नहीं है?',
    signUp: 'साइन अप करें',
    changeLanguage: 'भाषा बदलें',
    signUp2: 'साइन अप',
    enterFullName: 'पूरा नाम दर्ज करें',
    enterEmailId: 'ईमेल आईडी दर्ज करें',
    enterPhoneNo: 'फ़ोन नंबर दर्ज करें',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    newPassword: 'नया पासवर्ड',
    enterNewPassword: 'नया पासवर्ड दर्ज करें',
    resetPassword: 'पासवर्ड रीसेट करें',
    sendOtp: 'OTP भेजें',
    usePhoneNumber: 'फ़ोन नंबर का उपयोग करें',
    useEmail: 'ईमेल का उपयोग करें',
    verification: 'सत्यापन',
    enterOtpReceived: 'आपको प्राप्त हुए OTP दर्ज करें',
    verify: 'सत्यापित करें',
    didntReceivedOtp: 'OTP प्राप्त नहीं हुआ?',
    resendAgain: 'फिर से भेजें',
    otpError: 'OTP बिल्कुल 6 अक्षरों का होना चाहिए',
    new: 'नया',
    addImagesGallery: 'गैलरी से छवियाँ जोड़ें',
    createCard: 'अपना कार्ड बनाएं',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    save: 'सहेजें',
    contactUs: 'हमसे संपर्क करें',
    aboutUs: 'हमारे बारे में',
    logout: 'लॉग आउट',
    privacyPolicy: 'गोपनीयता और नीति',
    termsCondition: 'शर्तें और नियम',
    fullNameRequired: 'पूरा नाम आवश्यक है',
    fullNameError: 'पूरा नाम केवल अक्षर और अंतर को संज्ञान में लेता है',
    emailRequired: 'ईमेल आवश्यक है',
    emailError: 'अवैध ईमेल प्रारूप',
    phoneNoRequired: 'फोन नंबर आवश्यक है',
    phoneNoError: 'अवैध फोन नंबर प्रारूप',
    passwordRequired: 'पासवर्ड आवश्यक है',
    messageRequired: 'संदेश आवश्यक है',
    confirmPasswordRequired: 'पासवर्ड की पुष्टि की आवश्यकता है',
    confirmPasswordError: 'पासवर्ड मेल नहीं खाता',
    imageDownloaded: 'छवि डाउनलोड की गई!',
    liked: 'पसंद किया गया!',
    enterTextHere: 'यहां शब्द दर्ज करें ',
    changeYourName: 'अपना नाम बदलें',
    change: 'बदलें',
    name: 'नाम',
    edit: 'संपादित करें',
    selectImage: 'छवि चुनें',
    changeName: 'नाम बदलें',
    selectBackGround: 'पृष्ठभूमि चुनें',
    enterText: 'शब्द दर्ज करें',
    getInTouch: 'संपर्क में आओ',
    enterYourName: 'अपना नाम दर्ज करें',
    enterYourMessage: 'अपना संदेश दर्ज करें',
    submit: 'सबमिट करें',
    settings: 'सेटिंग्स',

    changeTextColor: 'शब्दों का रंग बदलें',
    changeNameColor: 'नाम का रंग बदलें',
    changeInfoColor: 'जानकारी का रंग बदलें',
    enterBirthdate: 'जन्म तारीख दर्ज करें',
    birthdateRequired: 'कृपया अपनी जन्म तारीख का चयन करें',
    //category
    goodMorning: 'शुभ प्रभात',
    goodNight: 'शुभ रात्रि',
    love: 'प्यार',
    motivational: 'प्रेरणादायक',
    festival: 'त्योहार',
    specialDay: 'विशेष दिन',
    devotional: 'धार्मिक',
    birthday: 'जन्मदिन',

    // about us section
    heading1: 'रोज़ाना बनाएं',
    heading2: 'अपनी अनूठी स्थिति SOCIFLY पर',
    dearUsers: 'Dear Users,',
    sociflyApp: '‘SOCIFLY APP’',
    point1:
      'Have a warm and helpful greeting from me. I am Dhiraj Gajendra Navlakhe the owner of this ',
    point2:
      '. I have completed advanced diploma in graphic designing and animation from IMR College Jalgaon, Maharashtra.',
    point3:
      'After that I am working as a freelance graphic designer from last 11 years. I am working with leading publication houses and advertising agencies from India, UK, US and Australia. Some of my clients are as follows.',
    point4:
      'Now I am starting this new app for all of you so that all of you can send your wishes to your friends, relatives and customers in very special way to create a new bonding with all of them.',
    point5: 'Kindly use the',
    point6: 'and give your love and likes to it.',
    point7: 'Also share the app and rate this app on Play Store.',
    point8: 'Have a nice day.',
    point9: 'Thank you',

    place1: 'Youkiyoto Publishing (Canada)',
    place2: 'Shildcrest Publishing (London, UK)',
    place3: 'Atmosphere Press (Austin, USA)',
    place4: 'Zorba Books (Gurgaon, India)',
    place5: 'Varada Prakashan (Pune, India)',
    place6: 'Youtbook (Chennai, India)',
  },
  ma: {
    welcome: 'आपले स्वागत आहे',
    emailOrPhone: 'ईमेल किंवा फोन नंबर',
    password: 'पासवर्ड',
    login: 'लॉगिन करा',
    forgotPassword: 'पासवर्ड विसरलात?',
    noAccount: 'खाते नाहीतर?',
    signUp: 'साइन अप करा',
    changeLanguage: 'भाषा बदला',
    signUp2: 'साइन अप',
    enterFullName: 'पूर्ण नाव प्रविष्ट करा',
    enterEmailId: 'ईमेल आयडी प्रविष्ट करा',
    enterPhoneNo: 'फोन नंबर प्रविष्ट करा',
    confirmPassword: 'पासवर्ड पुष्टीकरण करा',
    newPassword: 'नवीन पासवर्ड',
    enterNewPassword: 'नवीन पासवर्ड प्रविष्ट करा',
    resetPassword: 'पासवर्ड रीसेट करा',
    sendOtp: 'OTP पाठवा',
    usePhoneNumber: 'फोन नंबर वापरा',
    useEmail: 'ईमेल वापरा',
    verification: 'सत्यापन',
    enterOtpReceived: 'आपल्याला प्राप्त झालेला OTP प्रविष्ट करा',
    verify: 'सत्यापित करा',
    didntReceivedOtp: 'OTP प्राप्त झालेला नाही का?',
    resendAgain: 'पुन्हा पाठवा',
    otpError: 'OTP संपूर्णपणे 6 अक्षरांचा असावा',
    new: 'नविन',
    addImagesGallery: 'गॅलरीमधून चित्रे जोडा',
    createCard: 'आपला स्वत:चा कार्ड तयार करा',
    editProfile: 'प्रोफाइल संपादित करा',
    save: 'संचयन करा',
    contactUs: 'आमच्याशी संपर्क साधा',
    aboutUs: 'आमच्याबद्दल',
    logout: 'लॉगआउट',
    privacyPolicy: 'गोपनीयता व धोरण',
    termsCondition: 'अटी आणि अटीस',
    fullNameRequired: 'पूर्ण नाव आवश्यक आहे',
    fullNameError: 'पूर्ण नाव केवळ अक्षरे आणि जागा असू शकतात',
    emailRequired: 'ईमेल आवश्यक आहे',
    emailError: 'अयोग्य ईमेल प्रारूप',
    phoneNoRequired: 'फोन नंबर आवश्यक आहे',
    phoneNoError: 'अयोग्य फोन नंबर प्रारूप',
    passwordRequired: 'पासवर्ड आवश्यक आहे',
    messageRequired: 'संदेश आवश्यक आहे',
    confirmPasswordRequired: 'पासवर्डची पुष्टी आवश्यक आहे',
    confirmPasswordError: 'पासवर्डस मेल नाहीत',
    imageDownloaded: 'छवि डाउनलोड केली!',
    liked: 'पसंद केलं!',
    enterTextHere: 'येथे शब्द प्रविष्ट करा ',
    changeYourName: 'तुमचं नाव बदला',
    change: 'बदला',
    name: 'नाव',
    edit: 'संपादित करा',
    selectImage: 'चित्र निवडा',
    changeName: 'नाव बदला',
    selectBackGround: 'पृष्ठभूमी निवडा',
    enterText: 'शब्द प्रविष्ट करा',
    getInTouch: 'संपर्क साधा',
    enterYourName: 'तुमचं नाव प्रविष्ट करा',
    enterYourMessage: 'तुमचं संदेश प्रविष्ट करा',
    submit: 'सबमिट करा',
    settings: 'सेटिंग्स',

    changeTextColor: 'शब्दांचा रंग बदला',
    changeNameColor: 'नावाचा रंग बदला',
    changeInfoColor: 'माहितीचा रंग बदला',
    enterBirthdate: 'जन्म तारीख प्रविष्ट करा',
    birthdateRequired: 'कृपया आपली जन्म तारीख निवडा',
    //category
    goodMorning: 'सुप्रभात',
    goodNight: 'शुभ रात्री',
    love: 'प्रेम',
    motivational: 'प्रेरणास्पद',
    festival: 'उत्सव',
    specialDay: 'विशेष दिवस',
    devotional: 'धार्मिक',
    birthday: 'वाढदिवस',

    // about us section
    heading1: 'तुमचं दैनंदिन',
    heading2: 'अनूठी स्थिती SOCIFLY वर बनवा',
    dearUsers: 'प्रिय वापरकार्यांनो,',
    sociflyApp: '‘SOCIFLY APP’',
    point1:
      'माझ्याकडून तुमचं हार्दिक आणि सहाय्यक स्वागत आहे. माझं नाव धीरज गजेंद्र नवलखे आहे, ह्या ',
    point2:
      ' च्या मालक आहे. माझ्याकडून महाराष्ट्राच्या जळगावमधील आय.एम.आर. कॉलेजमधील ग्राफिक डिझायनिंग आणि ऍनिमेशनच्या सर्वोत्कृष्ट डिप्लोमा पूर्ण केलेला आहे.',
    point3:
      'त्यानंतर, माझ्याकडून पुढील 11 वर्षे एक स्वतंत्र ग्राफिक डिझायनर म्हणून काम करण्याची गोष्ट आहे. मी भारत, यूके, यूएस, आणि ऑस्ट्रेलियासह प्रमुख प्रकाशन प्रमाणित करणार्या घराण्याशी आणि जाहिराती ग्रुपसह काम करीत आहे. माझ्या काही ग्राहकांची यादी खालीलप्रमाणे आहे.',
    point4:
      'आता माझ्याकडून हे नवे ऍप्लिकेशन आपल्याला सर्वांसाठी सुखद आणि विशेषपणे तुमच्या मित्रांना, नातेवाईकांना, आणि ग्राहकांना आपल्याला त्यांच्या साथीसोबत एक नवीन जोडण्याच्या खास दारीसाठी आहे.',
    point5: ' कृपया ',
    point6: 'वापरा आणि त्याला आपल्याचं प्रेम आणि आवश्यकता आहे, हे द्या.',
    point7:
      'इ. त्याच्या अॅपवर दिलेल्या व्यक्तिगत म्हणजे तुमच्याला तुमच्या विनमूल्य मित्रांसोबत सुखद क्षण अनुभवायला हवं आणि आवश्यकता असल्यास त्याच्या अॅपवर रेट किंवा सामायिक करा.',
    point8: 'तुमच्याला आश्वासन आहे.',
    point9: 'धन्यवाद',

    place1: 'यूकियोटो प्रकाशन (कॅनडा)',
    place2: 'शिल्डक्रेस्ट प्रकाशन (लंडन, यूके)',
    place3: 'अँट्मॉस्फिअर प्रेस (ऑस्टिन, यूएस)',
    place4: 'झोर्बा बुक्स (गुडगाव, भारत) ',
    place5: 'वरद प्रकाशन (पुणे, भारत) ',
    place6: 'यौटबुक (चेन्नई, भारत)',
  },
});

export default strings;
